// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutMediaOverlay from '@/components/sections/about/AboutMediaOverlay';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutMediaOverlay
          tag="Our Heritage"
          title="A Blend of Nordic Design and Rice Mill Heritage"
          description="Spanning over 7 Rai, our cafe perfectly merges modern architecture with the nostalgic, warm soul of traditional teak wood rice mill construction."
          imageSrc="http://img.b2bpic.net/free-photo/beverage-baked-apples-near-napkin-leaves_23-2147885822.jpg"
        />
        </SectionErrorBoundary>
      </div>
  );
}
