// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutMediaOverlay from '@/components/sections/about/AboutMediaOverlay';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutMediaOverlay
          tag="มรดกของเรา"
          title="การผสมผสานระหว่างดีไซน์นอร์ดิกและตำนานโรงสีข้าว"
          description="บนพื้นที่กว่า 7 ไร่ คาเฟ่ของเราผสานสถาปัตยกรรมสมัยใหม่เข้ากับจิตวิญญาณอันอบอุ่นและกลิ่นอายของโรงสีข้าวไม้สักโบราณได้อย่างลงตัว"
          imageSrc="http://img.b2bpic.net/free-photo/beverage-baked-apples-near-napkin-leaves_23-2147885822.jpg"
        />
        </SectionErrorBoundary>
      </div>
  );
}
