// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Visit Us"
          text="Open Daily 07:30 - 23:00 | Chaniang, Mueang Surin District."
          primaryButton={{
            text: "Get Directions",        href: "https://maps.google.com"}}
          secondaryButton={{
            text: "Contact Us",        href: "mailto:hello@361.com"}}
        />
        </SectionErrorBoundary>
      </div>
  );
}
