// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialColumnMarqueeCards from '@/components/sections/testimonial/TestimonialColumnMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialColumnMarqueeCards
          tag="Voices"
          title="What Our Guests Say"
          description="Community stories from the heart of Surin."
          testimonials={[
            {
              name: "Alice Chen",          role: "Travel Blogger",          quote: "The architecture is stunning and the roastery is world-class.",          imageSrc: "http://img.b2bpic.net/free-photo/pretty-blonde-woman-sitting-cafe_273609-6756.jpg"},
            {
              name: "David Miller",          role: "Food Critic",          quote: "A unique blend of heritage and modern luxury. The shabu is incredible.",          imageSrc: "http://img.b2bpic.net/free-photo/portrait-one-black-american-female-eats-gourmet-vegetarian-meal-drinks-wine-restaurant_613910-7365.jpg"},
            {
              name: "Sarah Smith",          role: "Local Resident",          quote: "My favorite place for a weekend brunch with family.",          imageSrc: "http://img.b2bpic.net/free-photo/mix-asian-woman-caucasian-men-people-meeting-friendship-togetherness-happiness-enjoy-coffee-shop-concept-casual-relax-moment_609648-2392.jpg"},
            {
              name: "James Wong",          role: "Coffee Enthusiast",          quote: "The signature house blend has notes I've never tasted before.",          imageSrc: "http://img.b2bpic.net/free-photo/vertical-shot-gentle-tender-relaxed-urban-woman-wearing-glasses-enjoying-moment-sitting-alone-cafe_197531-22826.jpg"},
            {
              name: "Elena Rossi",          role: "Design Student",          quote: "An absolute masterclass in Nordic interior design.",          imageSrc: "http://img.b2bpic.net/free-photo/portrait-interesting-reddish-man-posing-with-coffee_158595-3757.jpg"},
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
