// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "zones" section.

import React from 'react';
import FeaturesBorderGlow from '@/components/sections/features/FeaturesBorderGlow';
import { Camera, Coffee, Utensils } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ZonesSection(): React.JSX.Element {
  return (
    <div id="zones" data-section="zones">
        <SectionErrorBoundary name="zones">
              <FeaturesBorderGlow
          tag="Our Zones"
          title="Experience the Landmark"
          description="Three unique areas designed to elevate your sensory experience."
          features={[
            {
              icon: Coffee,
              title: "Specialty Roastery",          description: "In-house roasted beans, featuring a curated selection from light to dark roasts."},
            {
              icon: Utensils,
              title: "Dining & Shabu",          description: "More than just a cafe, a complete family dining experience centered on quality."},
            {
              icon: Camera,
              title: "The Skywalk",          description: "Breathtaking views of the 7 Rai grounds, providing endless unique photo spots."},
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
